CREATE TABLE IF NOT EXISTS usuario(
	CPF CHAR(11) NOT NULL,
	Avaliacao INT DEFAULT '5',
	Email VARCHAR(100) NOT NULL,
	Senha VARCHAR(45) NOT NULL,
	BirdCoin INT DEFAULT '0',
	Nome VARCHAR(45) NOT NULL,
	Sobrenome VARCHAR(250) NOT NULL,
	Endereco VARCHAR(45) NOT NULL,
	PRIMARY KEY(CPF)
);